/**
 * Data CONTOH daftar kelas LMS untuk pratinjau visual "pintu masuk" (akses dengan ?demo=1).
 * BUKAN data nyata — strukturnya mengikuti respons backend `GET /lms/classes` (rows[]),
 * agar tampilan bisa dinilai sebelum endpoint SIAK v2 siap. Akan diabaikan saat data asli ada.
 */
export const SAMPLE_CLASSES = [
  {
    kelasKuliahId: "demo-kls-1",
    semester: "20241",
    nama_kelas: "TI-3A",
    prodi_id: "demo-prodi-ti",
    mata_kuliah_id: "demo-mk-oop",
    kode_matakuliah: "TIF2103",
    nama_matakuliah: "Pemrograman Berorientasi Objek",
    sks: 3,
    kode_prodi: "55201",
    nama_prodi: "Teknik Informatika",
    fakultas_id: "demo-ft",
    kode_fakultas: "FT",
    nama_fakultas: "Fakultas Teknik dan Sains",
    dosen_pengampu_nip: ["198801012015041001"],
    total_lecturers: 1,
    total_participants: 38,
    total_sections: 6,
  },
  {
    kelasKuliahId: "demo-kls-2",
    semester: "20241",
    nama_kelas: "TI-3B",
    prodi_id: "demo-prodi-ti",
    mata_kuliah_id: "demo-mk-basdat",
    kode_matakuliah: "TIF2105",
    nama_matakuliah: "Sistem Basis Data",
    sks: 3,
    kode_prodi: "55201",
    nama_prodi: "Teknik Informatika",
    fakultas_id: "demo-ft",
    kode_fakultas: "FT",
    nama_fakultas: "Fakultas Teknik dan Sains",
    dosen_pengampu_nip: ["199002022018032002", "198703032016041003"],
    total_lecturers: 2,
    total_participants: 41,
    total_sections: 8,
  },
  {
    kelasKuliahId: "demo-kls-3",
    semester: "20241",
    nama_kelas: "MJ-2A",
    prodi_id: "demo-prodi-mj",
    mata_kuliah_id: "demo-mk-mnj",
    kode_matakuliah: "MNJ1202",
    nama_matakuliah: "Pengantar Manajemen",
    sks: 2,
    kode_prodi: "61201",
    nama_prodi: "Manajemen",
    fakultas_id: "demo-fe",
    kode_fakultas: "FE",
    nama_fakultas: "Fakultas Ekonomi dan Bisnis",
    dosen_pengampu_nip: ["198509092014042004"],
    total_lecturers: 1,
    total_participants: 52,
    total_sections: 0,
  },
  {
    kelasKuliahId: "demo-kls-4",
    semester: "20232",
    nama_kelas: "TI-4A",
    prodi_id: "demo-prodi-ti",
    mata_kuliah_id: "demo-mk-rpl",
    kode_matakuliah: "TIF3110",
    nama_matakuliah: "Rekayasa Perangkat Lunak",
    sks: 3,
    kode_prodi: "55201",
    nama_prodi: "Teknik Informatika",
    fakultas_id: "demo-ft",
    kode_fakultas: "FT",
    nama_fakultas: "Fakultas Teknik dan Sains",
    dosen_pengampu_nip: ["198801012015041001"],
    total_lecturers: 1,
    total_participants: 35,
    total_sections: 12,
  },
];

// Daftar semester unik dari data contoh (untuk filter dropdown saat ?demo=1).
export const SAMPLE_SEMESTERS = ["20241", "20232"];
